//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomerCareMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Order
    {
        public int OrderId { get; set; }
        public Nullable<int> ProductId { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string CustomerName { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string PaymentMode { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public string Date { get; set; }

        public string Status { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public Nullable<int> Quantity { get; set; }

        [Required(ErrorMessage = "This field is required")]
        public Nullable<int> UnitPrice { get; set; }
        public Nullable<int> Total { get; set; }
    
        public virtual Order Order1 { get; set; }
        public virtual Order Order2 { get; set; }
        public virtual Product Product { get; set; }
    }
}
